name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        pio run -e odroid_esp32
        pio run -e hat
        pio run -e hat_PSRAM
        pio run -e Belge
        pio run -e Brian_Lough_64x32
        pio run -e Brian_Lough_64x64
        pio run -e m5stack
        
    - name: Deploy
      env:
        SUPER_SECRET: ${{ secrets.TOKEN }} 
      run: |
        mv .pio/build/odroid_esp32/firmware.bin firmware_odroid_esp32.bin
        mv .pio/build/hat/firmware.bin firmware_hat.bin
        mv .pio/build/hat_PSRAM/firmware.bin firmware_hat_PSRAM.bin
        mv .pio/build/Belge/firmware.bin firmware_Belge.bin
        mv .pio/build/Brian_Lough_64x32/firmware.bin Brian_Lough_64x32_firmware.bin
        mv .pio/build/Brian_Lough_64x64/firmware.bin Brian_Lough_64x64_firmware.bin
        mv .pio/build/m5stack/firmware.bin m5stack_firmware.bin

        curl -F file=@firmware_odroid_esp32.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -F file=@firmware_hat.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -F file=@firmware_hat_PSRAM.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -F file=@firmware_Belge.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -F file=@Brian_Lough_64x32_firmware.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -F file=@Brian_Lough_64x64_firmware.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -F file=@m5stack_firmware.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET

