name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build odroid_esp32
      run: pio run -e odroid_esp32
    - name: Build hat
      run: pio run -e hat
    - name: Build hat_PSRAM
      run: pio run -e hat_PSRAM
    - name: Build Belge
      run: pio run -e Belge
    - name: Build Brian_Lough_64x32
      run: pio run -e Brian_Lough_64x32
    - name: Build Brian_Lough_64x64
      run: pio run -e Brian_Lough_64x64
    - name: Build m5stack
      run: pio run -e m5stack
    - name: Build Belge_2_32x32
      run: pio run -e "Belge_2_32x32"
    - name: Deploy
      env:
        SUPER_SECRET: ${{ secrets.TOKEN }} 
      run: |
        mv .pio/build/odroid_esp32/firmware.bin firmware_odroid_esp32.bin
        mv .pio/build/hat/firmware.bin firmware_hat.bin
        mv .pio/build/hat_PSRAM/firmware.bin firmware_hat_PSRAM.bin
        mv .pio/build/Belge/firmware.bin firmware_Belge.bin
        mv .pio/build/Brian_Lough_64x32/firmware.bin firmware_Brian_Lough_64x32.bin
        mv .pio/build/Brian_Lough_64x64/firmware.bin firmware_Brian_Lough_64x64.bin
        mv .pio/build/m5stack/firmware.bin firmware_m5stack.bin
        mv .pio/build/Belge_2_32x32/firmware.bin firmware_Belge_2_32x32.bin

        curl -sSF file=@firmware_odroid_esp32.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@firmware_hat.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@firmware_hat_PSRAM.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@firmware_Belge.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@firmware_Brian_Lough_64x32.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@firmware_Brian_Lough_64x64.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@firmware_m5stack.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@firmware_Belge_2_32x32.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET

        echo `TZ="Europe/Paris" date '+%F %T'`" git:"`git rev-parse --short HEAD` > emote_matrix.info
        curl -sSF file=@emote_matrix.info 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET


